[/Script/StashUnreal.MyPlayerController]
; Stash API Configuration
; Set your API token here if it's not showing in Blueprint Class Defaults
ApiAuthToken=zyIbbfvO1ZRTaDt1VBZ5CJrwrdzyfDyLgt-VWNT-1uWj-5h42aeB6BNGAl8MGImw
CheckoutApiUrl=https://test-api.stash.gg/sdk/server/checkout_links/generate_quick_pay_url
